---
- name: fish directory
  file: path={{ home }}/.config/fish/functions state=directory owner={{ username }} group={{ groupname }} mode=0755

- stat: path={{ home }}/.config/fish/fishfile
  register: f
- name: create fishfile if not exists
  file: path={{ home }}/.config/fish/fishfile state=touch owner={{ username }} group={{ groupname }} mode=0644
  when: not f.stat.exists

- stat: path={{ home }}/.config/fish/dircolors-solarized
  register: f
- name: install solarized
  git: repo=https://github.com/seebi/dircolors-solarized dest=~/.config/fish/dircolors-solarized accept_hostkey=yes
  when: not f.stat.exists

- name: copy default config.fish
  copy: src=config.fish dest={{ home }}/.config/fish/config.fish  owner={{ username }} group={{ groupname }} mode=0644

- stat: path={{ home }}/.config/fish/functions/fisher.fish
  register: f
- name: install fisherman
  get_url: url=https://git.io/fisherman dest=~/.config/fish/functions/fisher.fish
  when: not f.stat.exists

  #- name: check fzf installation
  #  shell: grep -q '^fisherman/fzf$' {{ home }}/.config/fish/fishfile
  #  register: fzfcnt
  #  ignore_errors: true
  #
  #- name: install fisherman fzf-plugin
  #  shell: fisher fzf
  #  when: fzfcnt.rc != 0
  #
  #- name: check plugin-z installation
  #  shell: grep -q '^fisherman/z$' {{ home }}/.config/fish/fishfile
  #  register: zcnt
  #  ignore_errors: true
  #
  #- name: install fisherman z-plugin
  #  shell: fisher z
  #  when: zcnt.rc != 0

