---
- stat: path={{ home }}/.zgen
  register: f
- name: install zgen
  git: repo=https://github.com/tarjoilija/zgen.git dest=~/.zgen accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.zsh/dircolors-solarized
  register: f
- name: install solarized
  git: repo=https://github.com/seebi/dircolors-solarized dest=~/.zsh/dircolors-solarized accept_hostkey=yes
  when: not f.stat.exists

- name: copy default .zshrc
  copy: src=.zshrc dest={{ home }}/.zshrc owner={{ username }} group={{ groupname }} mode=0644

- name: copy default .zshrc-after
  copy: src=.zshrc-after dest={{ home }}/.zshrc-after owner={{ username }} group={{ groupname }} mode=0644

- name: copy default .tmux.conf
  copy: src=.tmux.conf dest={{ home }}/.tmux.conf owner={{ username }} group={{ groupname }} mode=0644

