---
- name: vim autoload directory
  file: path={{ home }}/.vim/autoload state=directory owner={{ username }} group={{ groupname }} mode=0755

- name: vim bundle directory
  file: path={{ home }}/.vim/bundle state=directory owner={{ username }} group={{ groupname }} mode=0755

- stat: path={{ home }}/.vim/autoload/pathogen.vim
  register: f
- name: install pathogen
  get_url: url=https://tpo.pe/pathogen.vim dest=~/.vim/autoload/pathogen.vim
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-elixir
  register: f
- name: install elixir syntax
  git: repo=https://github.com/elixir-lang/vim-elixir.git dest=~/.vim/bundle/vim-elixir accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-mix
  register: f
- name: install elixir mix
  git: repo=https://github.com/mattreduce/vim-mix.git dest=~/.vim/bundle/vim-mix accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-go
  register: f
- name: install vim-go
  git: repo=https://github.com/fatih/vim-go.git dest=~/.vim/bundle/vim-go accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/syntastic
  register: f
- name: install syntastic
  git: repo=https://github.com/scrooloose/syntastic.git dest=~/.vim/bundle/syntastic accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/nerdtree
  register: f
- name: install nerdtree
  git: repo=https://github.com/scrooloose/nerdtree.git dest=~/.vim/bundle/nerdtree accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-nerdtree-tabs
  register: f
- name: install nerdtree tabs
  git: repo=https://github.com/jistr/vim-nerdtree-tabs.git dest=~/.vim/bundle/vim-nerdtree-tabs accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-airline
  register: f
- name: install vim-airline
  git: repo=https://github.com/vim-airline/vim-airline.git dest=~/.vim/bundle/vim-airline accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-fugitive
  register: f
- name: install vim-fugitive
  git: repo=https://github.com/tpope/vim-fugitive.git dest=~/.vim/bundle/vim-fugitive accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-surround
  register: f
- name: install vim-surround
  git: repo=https://github.com/tpope/vim-surround.git dest=~/.vim/bundle/vim-surround accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/onedark.vim
  register: f
- name: install onedark.vim
  git: repo=https://github.com/joshdick/onedark.vim.git dest=~/.vim/bundle/onedark.vim accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-polyglot
  register: f
- name: install vim-polyglt
  git: repo=https://github.com/sheerun/vim-polyglot.git dest=~/.vim/bundle/vim-polyglot accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-trailing-whitespace
  register: f
- name: install vim-trailing-whitespace
  git: repo=https://github.com/bronson/vim-trailing-whitespace.git dest=~/.vim/bundle/vim-trailing-whitespace accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-indent-guides
  register: f
- name: install indent guides
  git: repo=https://github.com/nathanaelkane/vim-indent-guides.git dest=~/.vim/bundle/vim-indent-guides accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-endwise
  register: f
- name: install endwise
  git: repo=https://github.com/tpope/vim-endwise.git dest=~/.vim/bundle/vim-endwise accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-autoclose
  register: f
- name: install autoclose
  git: repo=https://github.com/Townk/vim-autoclose.git dest=~/.vim/bundle/vim-autoclose accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/fzf.vim
  register: f
- name: install autoclose
  git: repo=https://github.com/junegunn/fzf.vim.git dest=~/.vim/bundle/fzf.vim accept_hostkey=yes
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/ag.vim
  register: f
- name: install autoclose
  git: repo=https://github.com/rking/ag.vim.git dest=~/.vim/bundle/ag.vim accept_hostkey=yes
  when: not f.stat.exists

- name: copy default .vimrc
  copy: src=.vimrc dest={{ home }}/.vimrc owner={{ username }} group={{ groupname }} mode=0644

