---
- name: vim autoload directory
  file: path={{ home }}/.vim/autoload state=directory owner={{ username }} group={{ groupname }} mode=0755

- name: vim bundle directory
  file: path={{ home }}/.vim/bundle state=directory owner={{ username }} group={{ groupname }} mode=0755

- stat: path={{ home }}/.vim/autoload/pathogen.vim
  register: f
- name: install pathogen
  shell: curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-elixir
  register: f
- name: install elixir syntax
  shell: git clone https://github.com/elixir-lang/vim-elixir.git ~/.vim/bundle/vim-elixir
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-mix
  register: f
- name: install elixir mix
  shell: git clone https://github.com/mattreduce/vim-mix.git ~/.vim/bundle/vim-mix
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-go
  register: f
- name: install vim-go
  shell: git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/syntastic
  register: f
- name: install syntastic
  shell: git clone https://github.com/scrooloose/syntastic.git ~/.vim/bundle/syntastic
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/nerdtree
  register: f
- name: install nerdtree
  shell: git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-nerdtree-tabs
  register: f
- name: install nerdtree tabs
  shell: git clone https://github.com/jistr/vim-nerdtree-tabs.git ~/.vim/bundle/vim-nerdtree-tabs
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-airline
  register: f
- name: install vim-airline
  shell: git clone https://github.com/vim-airline/vim-airline.git ~/.vim/bundle/vim-airline
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-fugitive
  register: f
- name: install vim-fugitive
  shell: git clone https://github.com/tpope/vim-fugitive.git ~/.vim/bundle/vim-fugitive
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/onedark.vim
  register: f
- name: install onedark.vim
  shell: git clone https://github.com/joshdick/onedark.vim.git ~/.vim/bundle/onedark.vim
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-polyglot
  register: f
- name: install vim-polyglt
  shell: git clone https://github.com/sheerun/vim-polyglot.git ~/.vim/bundle/vim-polyglot
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-trailing-whitespace
  register: f
- name: install vim-trailing-whitespace
  shell: git clone https://github.com/bronson/vim-trailing-whitespace.git ~/.vim/bundle/vim-trailing-whitespace
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-indent-guides
  register: f
- name: install indent guides
  shell: git clone https://github.com/nathanaelkane/vim-indent-guides.git ~/.vim/bundle/vim-indent-guides
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/neocomplete.vim
  register: f
- name: install neocomplete
  shell: git clone https://github.com/Shougo/neocomplete.vim.git ~/.vim/bundle/neocomplete.vim
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-endwise
  register: f
- name: install endwise
  shell: git clone https://github.com/tpope/vim-endwise.git ~/.vim/bundle/vim-endwise
  when: not f.stat.exists

- stat: path={{ home }}/.vim/bundle/vim-autoclose
  register: f
- name: install autoclose
  shell: git clone https://github.com/Townk/vim-autoclose.git ~/.vim/bundle/vim-autoclose
  when: not f.stat.exists

- name: copy default .vimrc
  copy: src=.vimrc dest={{ home }}/.vimrc owner={{ username }} group={{ groupname }} mode=0644

